// <auto-generated />
using App.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210317113805_CreateUsersTable")]
    partial class CreateUsersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("App.Models.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("Badges")
                        .HasColumnType("char")
                        .HasColumnName("badges");

                    b.Property<string>("DoneQuests")
                        .HasColumnType("char")
                        .HasColumnName("done_quests");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("char(250)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("char(250)")
                        .HasColumnName("password");

                    b.Property<string>("TakenQuests")
                        .HasColumnType("char")
                        .HasColumnName("taken_quests");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("char(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "First",
                            Email = "stub@stub.com",
                            Password = "12345",
                            UserName = "Márton Szabó"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
